apiVersion: batch/v1
kind: Job
metadata:
  name: multi-pod-job
spec:
  completions: 3
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
      - command:
        - sleep
        - "10"
        image: busybox
        name: multi-pod-job
        resources: {}
      restartPolicy: Never
status: {}
