apiVersion: v1
kind: ConfigMap
metadata:
  name: fibonacci-configmap
data:
  REDIS_HOST: redis-service
  REDIS_PORT: '6379'
  PGHOST: postgres-service
  PGPORT: '5432'
  PGDATABASE: fibonacci