apiVersion: v1                  #Pod resource is under the scope of v1
kind: Pod                       #one type of resource that can be deployed in k8s nodes. Most of the time contains only one container.
#                               #k8s is not designed to run containers, but can deploy pods that has atleast one running containers. 
#                               #a senario to run other containers in same pod is when their entire functionality depends solely on the primary container.
metadata:
  name: react-pod               #name of the pod. Used for debugging/troubleshooting/logging. Must be unique in a namespace.
  labels:                       #key-value pair we created to be used as pod identifier. Can be reused.
    component: frontend         #service.yaml refers to this pod with its selector:.
spec:
  containers:
  - name: react                 #identifier of the container in the pod. Used for logging and pod intranet.
    image: betzdockz/fib-react
    imagePullPolicy: Never      #Default is Always. Never is used to force node to use local image.
    resources:                  #min-max resources that the container is allowed to operate within.  
      requests:                 #If k8s scheduler cannot find a single node in which below cpu and ram can be reserved, then pod be pending(status) and will not start.
        memory: "64Mi"          #memory without suffix is in bytes. Allowed suffixes are Ti, Gi, Mi, Ki, T, G, M, k.
        cpu: "250m"             #cpu without suffix is number of cores. Use suffix of m to specify millicores. 1000m = 1 core.
      limits:                   #These limits are enforced by kublet and kernel of the node the pod is running on.
        memory: "128Mi"         #If mem limit is exceeded, pod will be terminated with OOMKilled status. This will cause the pod to restart.
        cpu: "500m"             #system kernel will begin cpu throttling at this limit. Pod can still run, but will experience performance bottleneck.
    ports:
      - containerPort: 3000